version: "3"
services:
  todoback:
    image: todobackend
    restart: on-failure
    ports:
      - 3001:3001

  todofront:
    image: todofrontend
    restart: on-failure
    ports:
      - 3000:3000
    depends_on:
      - todobackend
    environment:
      - REACT_APP_API_HOST=todobackend

  todotests:
    image: todotests
    restart: on-failure
    depends_on:
      - todobackend
      - todofrontend
    environment:
      - FRONT_HOST=todofrontend
